export const producten = [
    {
        "id": 8,
        "volgnummer": 8,
        "product": "HQ AA Alkaline",
        "omschrijving": "Goede alkaline batterijen voor algemeen gebruik. <br \/><br \/>Per 4 stuks in een folie verpakt. Neemt weinig ruimte in en geven weinig afval.<br \/><br \/>Lang houdbaar.<br \/><br \/><br \/>De verplichte Verwijderingsbijdrage is in de totaalprijs opgenomen (0,02 per batterij).<br \/>",
        "categorie": "batterijen",
        "type": "AA",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "30.7200",
        "prijsperstuk": "0.2100",
        "verzendkosten": null,
        "bestelhoeveelheid": 96,
        "leverancier": "HQ-ALK-AA-03",
        "picture": "~\/images\/AAAalkaline4.jpg",
        "pdf": null,
        "prijs2": "60.0000",
        "bestelhoeveelheid2": 240,
        "prijs3": "201.6000",
        "bestelhoeveelheid3": 960,
        "Nieuw": null
    },
    {
        "id": 12,
        "volgnummer": 14,
        "product": "HQ D alkaline",
        "omschrijving": "D-alkaline batterijen (LR20) per twee stuks in blister. Bestelhoeveelheid is 12 stuks.<br \/><br \/>Hoogte: 60,5 mm.<br \/>Diameter: 32,8 mm.<br \/>Voltage:1,5 V<br \/><br \/>De verplichte Verwijderingsbijdrage is in de prijs opgenomen (0,06 per batterij).<br \/><br \/>Andere aantallen nodig? Mail voor een aanbieding op maat naar Info@Fetum.nl.",
        "categorie": "batterijen",
        "type": "D",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "16.2000",
        "prijsperstuk": "1.2900",
        "verzendkosten": null,
        "bestelhoeveelheid": 12,
        "leverancier": "Nedis artikelnr: HQ-LR20 ",
        "picture": "~\/images\/Dalkaline.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 13,
        "volgnummer": 15,
        "product": "HQ 9V block",
        "omschrijving": "9V block batterijen per stuk in blister. Bestelhoeveelheid is 10 stuks.<br \/><br \/>De verplichte Verwijderingsbijdrage is in de prijs opgenomen (0,06 per batterij).<br \/><br \/>Andere aantallen nodig? Mail voor een aanbieding op maat naar Info@Fetum.nl.",
        "categorie": "batterijen",
        "type": "9V",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "15.2000",
        "prijsperstuk": "1.4600",
        "verzendkosten": null,
        "bestelhoeveelheid": 10,
        "leverancier": "Nedis artikelnr: HQ-LR22",
        "picture": "~\/images\/9Vblock.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    }, {
        "id": 29,
        "volgnummer": 141,
        "product": "Hoofdtelefoonsplitter",
        "omschrijving": "Met deze splitter kunnen twee hoofdtelefoons op 1 aansluiting worden aangesloten, zonder geluidsverlies.<br \/><br \/>Kleur: wit.<br \/>Aansluitingen: 3,5 mm stereo<br \/><br \/>verpakking: per stuk in blister",
        "categorie": "hoofdtelefoon accessoires",
        "type": "splitter",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "59.8000",
        "prijsperstuk": "2.9900",
        "verzendkosten": null,
        "bestelhoeveelheid": 20,
        "leverancier": "Nedis artikelnr: IPD-EARSPLIT10 (20 stuks)",
        "picture": "~\/images\/splitter.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 71,
        "volgnummer": 800,
        "product": "USB verlengkabel (3 meter)",
        "omschrijving": "USB verlengkabel met een lengte van 3 meter.<br \/>Geschikt voor USB 2.0 datasnelheden.<br \/><br \/>Grotere aantallen nodig? Stuur een email naar Info@Fetum.nl voor een passende aanbieding.",
        "categorie": "usb kabels",
        "type": "USB verleng",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "6.9600",
        "prijsperstuk": "3.4800",
        "verzendkosten": null,
        "bestelhoeveelheid": 2,
        "leverancier": "NEDIS artikelnr: CABLE-143\/3HS (2 stuks)",
        "picture": "~\/images\/A10003.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 72,
        "volgnummer": 805,
        "product": "USB A-B  (3 meter)",
        "omschrijving": "USB kabel A naar B met een lengte van 3 meter.<br \/>Grotere aantallen nodig? Stuur een email naar Info@Fetum.nl voor een passende aanbieding.",
        "categorie": "usb kabels",
        "type": "USB A-B",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "6.7800",
        "prijsperstuk": "3.3900",
        "verzendkosten": null,
        "bestelhoeveelheid": 2,
        "leverancier": "NEDIS artikelnr: CABLE-141\/3HS (2 stuks)",
        "picture": "~\/images\/A10010.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 73,
        "volgnummer": 806,
        "product": "USB A-B  (5 meter)",
        "omschrijving": "USB A naar B kabel met een lengte van 5 meter.<br \/>Grotere aantallen nodig? Stuur een email naar Info@Fetum.nl voor een passende aanbieding.",
        "categorie": "usb kabels",
        "type": "USB A-B",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "10.5200",
        "prijsperstuk": "5.2600",
        "verzendkosten": null,
        "bestelhoeveelheid": 2,
        "leverancier": "NEDIS artikelnr: CABLE-141\/5HS (3 stuks)",
        "picture": "~\/images\/A10010.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 74,
        "volgnummer": 808,
        "product": "USB A-mini 5P 3.0",
        "omschrijving": "USB A naar B mini 5-polig.<br \/>Geschikt voor o.a. het aansluiten van digitale camera of externe geheugen.<br \/><br \/>Lengte van de kabel is 3 meter.<br \/><br \/>Grotere aantallen nodig? Stuur een email naar Info@Fetum.nl voor een passende aanbieding.",
        "categorie": "usb kabels",
        "type": "USB A-5P",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "7.7800",
        "prijsperstuk": "3.8900",
        "verzendkosten": null,
        "bestelhoeveelheid": 2,
        "leverancier": "NEDIS artikelnr: CABLE-161\/3 (2 stuks)",
        "picture": "~\/images\/A 10011.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 75,
        "volgnummer": 204,
        "product": "Muis 55",
        "omschrijving": "Blauwe platte muis met 2 toetsen en scroll wiel.<br \/><br \/>1,2 meter snoer met USB aansluiting. Doordat er geen bewegende delen zijn een lange levensduur.<br \/><br \/>De platte muis is ook met kleine handjes goed te gebruiken.<br \/><br \/><br \/>Muis van goede kwaliteit en uitstekende prijs kwaliteits verhouding.<br \/><br \/><br \/>Download de PDF voor meer informatie.<br \/>.",
        "categorie": "muizen",
        "type": "USB",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "50.9000",
        "prijsperstuk": "4.3200",
        "verzendkosten": null,
        "bestelhoeveelheid": 10,
        "leverancier": "Sweex ",
        "picture": "~\/images\/muis-55-met-achtergrond-voor-site.jpg",
        "pdf": "~\/pdffiles\/muis 55 nw.pdf",
        "prijs2": "98.6000",
        "bestelhoeveelheid2": 20,
        "prijs3": "172.8000",
        "bestelhoeveelheid3": 40,
        "Nieuw": null
    },
    {
        "id": 80,
        "volgnummer": 220,
        "product": "Toetsenbord USB",
        "omschrijving": "Luxe en comfortabel Multimedia toetsenbord met USB aansluiting.<br \/><br \/>Nederlandse uitvoering (QWERTY)<br \/><br \/>104 toetsen + 18 multimedia toetsen voor het snel opstarten van toepassingen zoals internet en email.<br \/><br \/>Uitstekende prijs kwaliteit verhouding<br \/><br \/>LxBxH: 46x17x2 [cm]<br \/>kleur: zwart<br \/><br \/>Download de PDF voor meer informatie<br \/><br \/>Netwerkkabels nodig? Kijk bij 'accessoires' voor FTP-producten.",
        "categorie": "toetsenborden",
        "type": "USB",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "47.9400",
        "prijsperstuk": "7.9900",
        "verzendkosten": null,
        "bestelhoeveelheid": 6,
        "leverancier": "NEDIS artikelnr: CMP-KB50\/NL (7 stuks)",
        "picture": "~\/images\/ToetsenbordMultiUSB.jpg",
        "pdf": "~\/pdffiles\/usbtoetsenbord.pdf",
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 83,
        "volgnummer": 500,
        "product": "LCD muurbeugel",
        "omschrijving": "Muurbeugel voor LCD schermen van 14 tot maximaal 22 inch (55 cm) en\/of 15 kg. Deze beugel is draaibaar en kantelbaar en biedt daardoor veel flexibiliteit in de positie van het scherm.<br \/><br \/>Draaibaar: 90 graden<br \/>Kantelbaar: 20 graden<br \/>Afstand tot muur: 9 [cm]<br \/>Kleur: zilver<br \/>VESA: 50\/75\/100",
        "categorie": "TV beugel",
        "type": "Draai - kantelbaar",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "23.0000",
        "prijsperstuk": "18.0000",
        "verzendkosten": null,
        "bestelhoeveelheid": 1,
        "leverancier": "Fetum LCD-401(www.lumi.cn)",
        "picture": "~\/images\/LCD1420muur.jpg",
        "pdf": null,
        "prijs2": "21.0000",
        "bestelhoeveelheid2": 5,
        "prijs3": "18.0000",
        "bestelhoeveelheid3": 10,
        "Nieuw": null
    },
    {
        "id": 87,
        "volgnummer": 146,
        "product": "Hoofdtelefoon verlengsnoer",
        "omschrijving": "1,2 meter (krul)verlengsnoer voor 3,5 mm plug hoofdtelefoons.<br \/>Maximaal tot 3 meter uit te rekken. <br \/><br \/>Verpakking per 20 stuks, <br \/><br \/>Ideaal te gebruiken als de computer op grotere afstand staat en de hoofdtelefoon aansluiting aan de achterzijde van de pc is. Bij het weglopen schiet de hoofdtelefoon stekker uit de verlengkabel en blijft de geluidskaart onbeschadigd",
        "categorie": "hoofdtelefoon accessoires",
        "type": "verleng snoer",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "34.0000",
        "prijsperstuk": "1.7000",
        "verzendkosten": null,
        "bestelhoeveelheid": 20,
        "leverancier": "Nedis: CABLE-405 (20 stuks)",
        "picture": "~\/images\/verlengKrul.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 98,
        "volgnummer": 120,
        "product": "HP-136 N",
        "omschrijving": "Gesloten zeer solide hoofdtelefoon voor langdurig intensief gebruik.<br \/><br \/>Zeer stevig, met nylon omwikkeld snoer van 1,1 meter lengte. Enkelzijdig snoer, vanuit linker oorschelp.<br \/><br \/>Uitstekend geschikt voor onderwijstoepassingen waar nog wel eens op snoeren wordt gekauwd.<br \/><br \/>Dit is de 3e generatie van deze hoofdtelefoon. Per stuk in een opbergtas verpakt en voorzien van een stevige stekker.<br \/><br \/>Kleur:           zwart<br \/>Snoer:          lengte 1,1 meter<br \/>Aansluiting:  3,5 mm rechte stereo stekker<br \/>Verpakking:  per stuk in herbruikbare tas, per 32 in doos<br \/><br \/>Download de PDF voor meer informatie",
        "categorie": "hoofdtelefoons",
        "type": "degelijk",
        "eigenschap": null,
        "groep": "Winkelier",
        "prijs": "219.5200",
        "prijsperstuk": "6.2400",
        "verzendkosten": null,
        "bestelhoeveelheid": 32,
        "leverancier": "Nedis HQ-HP136",
        "picture": "~\/images\/HP136.jpg",
        "pdf": "~\/pdffiles\/HP-136.pdf",
        "prijs2": "424.9600",
        "bestelhoeveelheid2": 64,
        "prijs3": "798.7200",
        "bestelhoeveelheid3": 128,
        "Nieuw": null
    },
    {
        "id": 100,
        "volgnummer": 502,
        "product": "Vaste muurbeugel",
        "omschrijving": "Vaste muurbeugel voor flatscreens van 19 tot 22 inch<br \/><br \/>De beugel is slechts een cm dik en wordt heel plat tegen de muurbevestigd. De beugel beschikt over een anti diefstal beveiliging<br \/><br \/>Maximale gewicht: 20 kg<br \/>Kleur: zwart<br \/>Draaibaar: nee<br \/>Kantelbaar: nee<br \/>VESA: 50\/75\/100",
        "categorie": "TV beugel",
        "type": "Vaste bevestiging",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "17.0000",
        "prijsperstuk": "12.0000",
        "verzendkosten": null,
        "bestelhoeveelheid": 1,
        "leverancier": "NEDIS artikelnr: TVS-LCD05B",
        "picture": "~\/images\/TVS-LCD05B.jpg",
        "pdf": "~\/pdffiles\/19-26 inch vast antidiefstal.pdf",
        "prijs2": "14.0000",
        "bestelhoeveelheid2": 5,
        "prijs3": "12.0000",
        "bestelhoeveelheid3": 10,
        "Nieuw": null
    },
    {
        "id": 131,
        "volgnummer": 761,
        "product": "Netsnoer 8 Zwart",
        "omschrijving": "220V netsnoer met achtvormige plug.<br \/><br \/>Lengte: 2,5 meter<br \/>Kleur: zwart",
        "categorie": "accessoires",
        "type": "220V",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "8.5000",
        "prijsperstuk": "1.7000",
        "verzendkosten": null,
        "bestelhoeveelheid": 5,
        "leverancier": "Nedis: CABLE-701-2.5 (5 stuks)",
        "picture": "~\/images\/CABLE-8.JPG",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 132,
        "volgnummer": 762,
        "product": "Netsnoer 8 Wit",
        "omschrijving": "220V netsnoer met achtvormige plug.<br \/><br \/>Lengte: 1,5 meter<br \/>Kleur: wit",
        "categorie": "accessoires",
        "type": "220V",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "10.9000",
        "prijsperstuk": "2.1800",
        "verzendkosten": null,
        "bestelhoeveelheid": 5,
        "leverancier": "Nedis: CABLE-704\/W (5 stuks)",
        "picture": "~\/images\/CABLE-8W.JPG",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 133,
        "volgnummer": 763,
        "product": "Netsnoer laptop",
        "omschrijving": "220V netsnoer voor laptops.<br \/><br \/>Lengte: 1,8 meter<br \/>Kleur: zwart",
        "categorie": "accessoires",
        "type": "220V",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "14.7000",
        "prijsperstuk": "2.9400",
        "verzendkosten": null,
        "bestelhoeveelheid": 5,
        "leverancier": "Nedis: CABLE-712 (5 stuks)",
        "picture": "~\/images\/CABLE-LT.JPG",
        "pdf": "",
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 134,
        "volgnummer": 764,
        "product": "Netsnoer met randaarde",
        "omschrijving": "220V netsnoer met randaarde.<br \/><br \/>Lengte: 1,8 meter<br \/>Kleur: zwart",
        "categorie": "accessoires",
        "type": "220V",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "13.9000",
        "prijsperstuk": "2.7800",
        "verzendkosten": null,
        "bestelhoeveelheid": 5,
        "leverancier": "Nedis: CABLE-703 (5 stuks)",
        "picture": "~\/images\/CABLE-EURO.JPG",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 135,
        "volgnummer": 765,
        "product": "Stekkerdoos 3X",
        "omschrijving": "3-voudige stekkerdoos.<br \/><br \/>Uitgang: 3x SCHUKO<br \/>Kleur: wit<br \/>Kabellengte: 1,5 m",
        "categorie": "accessoires",
        "type": "220V",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "19.4000",
        "prijsperstuk": "4.8500",
        "verzendkosten": null,
        "bestelhoeveelheid": 4,
        "leverancier": "Nedis: EL-PS240B-HQ (4 stuks)",
        "picture": "~\/images\/EL-3xwit.JPG",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 136,
        "volgnummer": 766,
        "product": "Stekkerdoos 6X",
        "omschrijving": "6-voudige stekkerdoos.<br \/><br \/>Uitgang: 6x SCHUKO<br \/>Kleur: wit<br \/>Kabellengte: 1,5 m",
        "categorie": "accessoires",
        "type": "220V",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "21.8000",
        "prijsperstuk": "5.4500",
        "verzendkosten": null,
        "bestelhoeveelheid": 4,
        "leverancier": "Nedis: EL-PS060W1-HQ (4 stuks)",
        "picture": "~\/images\/EL-6xwit.JPG",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 137,
        "volgnummer": 767,
        "product": "Haspel 10m",
        "omschrijving": "Compacte en lichtgewicht kabelhaspel gemaakt van breekvast plastic.<br \/><br \/>Vier SCHUKO contacten en een indicatielamp voor oververhitting.",
        "categorie": "accessoires",
        "type": "220V",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "18.3700",
        "prijsperstuk": "18.3700",
        "verzendkosten": null,
        "bestelhoeveelheid": 1,
        "leverancier": "Nedis: BN-HASP08 (1 stuk)",
        "picture": "~\/images\/BN-HASPEL.JPG",
        "pdf": "",
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 150,
        "volgnummer": 31,
        "product": "CR2032 Lithium 3V",
        "omschrijving": "Voltage: 3V<br \/>Capaciteit: 220 mAh<br \/>Afmetingen: 20 x 3,2 [mm]<br \/><br \/>Deze batterij is geschikt voor de Sanyo Clonebox.<br \/><br \/>",
        "categorie": "batterijen",
        "type": "Knoopcel",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "4.7500",
        "prijsperstuk": "0.9500",
        "verzendkosten": null,
        "bestelhoeveelheid": 5,
        "leverancier": "Nedis: CR2032 (5 stuks)",
        "picture": "~\/images\/CR2032.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 165,
        "volgnummer": 773,
        "product": "FTP kabel (1 meter)",
        "omschrijving": "Folie afgeschermde CAT5e FTP patch kabel.<br \/><br \/>Lengte: 1 meter<br \/>Kleur: grijs<br \/><br \/>andere kleuren zijn verkrijgbaar, informeer via info@fetum.nl naar de mogelijkheden.",
        "categorie": "Netwerk kabels",
        "type": "FTP",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "8.7500",
        "prijsperstuk": "1.7500",
        "verzendkosten": null,
        "bestelhoeveelheid": 5,
        "leverancier": "Nedis: FTP-0007\/1 (5 stuks)",
        "picture": "~\/images\/FTPkabel.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 166,
        "volgnummer": 774,
        "product": "FTP kabel (2 meter)",
        "omschrijving": "Folie afgeschermde CAT5e FTP patch kabel.<br \/><br \/>Lengte: 2 meter<br \/>Kleur: grijs<br \/><br \/>andere kleuren zijn verkrijgbaar, informeer via info@fetum.nl naar de mogelijkheden.",
        "categorie": "Netwerk kabels",
        "type": "FTP",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "12.1500",
        "prijsperstuk": "2.4300",
        "verzendkosten": null,
        "bestelhoeveelheid": 5,
        "leverancier": "Nedis: FTP-0007\/2 (5 stuks)",
        "picture": "~\/images\/FTPkabel.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 167,
        "volgnummer": 775,
        "product": "FTP kabel (5 meter)",
        "omschrijving": "Folie afgeschermde CAT5e FTP patch kabel.<br \/><br \/>Lengte: 5 meter<br \/>Kleur: grijs<br \/><br \/>andere kleuren zijn verkrijgbaar, informeer via info@fetum.nl naar de mogelijkheden.",
        "categorie": "Netwerk kabels",
        "type": "FTP",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "19.5500",
        "prijsperstuk": "3.9100",
        "verzendkosten": null,
        "bestelhoeveelheid": 5,
        "leverancier": "Nedis: FTP-0007\/5 (5 stuks)",
        "picture": "~\/images\/FTPkabel.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 168,
        "volgnummer": 776,
        "product": "FTP kabel (10 meter)",
        "omschrijving": "Folie afgeschermde CAT5e FTP patch kabel.<br \/><br \/>Lengte: 10 meter<br \/>Kleur: grijs",
        "categorie": "Netwerk kabels",
        "type": "FTP",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "23.8000",
        "prijsperstuk": "5.9500",
        "verzendkosten": null,
        "bestelhoeveelheid": 4,
        "leverancier": "Nedis: FTP-0007\/10 (4 stuks)",
        "picture": "~\/images\/FTPkabel.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 169,
        "volgnummer": 777,
        "product": "FTP kabel (15 meter)",
        "omschrijving": "Folie afgeschermde CAT5e FTP patch kabel.<br \/><br \/>Lengte: 15 meter<br \/>Kleur: grijs",
        "categorie": "Netwerk kabels",
        "type": "FTP",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "16.2200",
        "prijsperstuk": "8.1100",
        "verzendkosten": null,
        "bestelhoeveelheid": 2,
        "leverancier": "Nedis: FTP-0007\/15 (2 stuks)",
        "picture": "~\/images\/FTPkabel.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 170,
        "volgnummer": 778,
        "product": "FTP kabel (20 meter)",
        "omschrijving": "Folie afgeschermde CAT5e FTP patch kabel.<br \/><br \/>Lengte: 20 meter<br \/>Kleur: grijs",
        "categorie": "Netwerk kabels",
        "type": "FTP",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "22.1600",
        "prijsperstuk": "11.0800",
        "verzendkosten": null,
        "bestelhoeveelheid": 2,
        "leverancier": "Nedis: FTP-0007\/20 (2 stuks)",
        "picture": "~\/images\/FTPkabel.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 171,
        "volgnummer": 779,
        "product": "FTP kabel (30 meter)",
        "omschrijving": "Folie afgeschermde CAT5e FTP patch kabel.<br \/><br \/>Lengte: 30 meter<br \/>Kleur: grijs",
        "categorie": "Netwerk kabels",
        "type": "FTP",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "26.4200",
        "prijsperstuk": "13.2100",
        "verzendkosten": null,
        "bestelhoeveelheid": 2,
        "leverancier": "Nedis: FTP-0007\/30 (2 stuks)",
        "picture": "~\/images\/FTPkabel.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 172,
        "volgnummer": 781,
        "product": "FTP kabel tester",
        "omschrijving": "Geschikt voor het testen van RJ45, RJ11, USB en UTP\/FTP kabels.<br \/><br \/>De ingebouwde microcontroller test op verschillende mogelijkheden; open verbinding, kortsluiting, verkeerd bekabeld en aardingsproblemen.<br \/>Het resultaat wordt via leds weergegeven.<br \/><br \/>Bespaar tijd en ergenis met deze kabeltester!",
        "categorie": "Netwerk kabels",
        "type": "FTP",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "41.6700",
        "prijsperstuk": "41.6700",
        "verzendkosten": null,
        "bestelhoeveelheid": 1,
        "leverancier": "Nedis; CMP-RCT20 ( 1 )",
        "picture": "~\/images\/RJ45tester.JPG",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 173,
        "volgnummer": 780,
        "product": "FTP kabelset",
        "omschrijving": "FTP kabelset bestaande uit:<br \/><br \/>100 meter dubbel afgeschermde kabel welke ongevoelig is voor elektrische invloeden van buitenaf.<br \/><br \/>Acht RJ45 connectoren met beschermhuls.<br \/><br \/>Een RJ45-tang waarmee de connectoren kunnen worden gemonteerd.",
        "categorie": "Netwerk kabels",
        "type": "FTP",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "69.0000",
        "prijsperstuk": "69.0000",
        "verzendkosten": null,
        "bestelhoeveelheid": 1,
        "leverancier": "Nedis: CMP-NWS5R100 (1) + ISDN-0025 (8) +TEL-0082",
        "picture": "~\/images\/kabelset.JPG",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 174,
        "volgnummer": 784,
        "product": "Switch SW8",
        "omschrijving": "Met deze Switch kan een netwerk snel worden uitgebreid waardoor er zeven extra pc's kunnen worden aangesloten.<br \/><br \/>Elke netwerkpoort van deze Switch is geschikt als uplink-poort, wat inhoudt dat er gemakkelijk andere switches aangesloten kunnen worden om het netwerk nog verder uit te breiden.<br \/><br \/>Snelheid: 10\/100 Mbps",
        "categorie": "computer netwerk",
        "type": "switch",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "85.0000",
        "prijsperstuk": "19.9000",
        "verzendkosten": null,
        "bestelhoeveelheid": 5,
        "leverancier": "Nedis: CMP-EHUB25 ",
        "picture": "~\/images\/sw-8site.jpg",
        "pdf": null,
        "prijs2": "19.9000",
        "bestelhoeveelheid2": 1,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 175,
        "volgnummer": 222,
        "product": "standaard toestenbord (zwart\/zilver)",
        "omschrijving": "Basic toetsenbord in zilver\/zwart voor een zeer scherpe prijs!<br \/><br \/>Aansluiting: PS2<br \/>Internationale (NL) layout<br \/><br \/>LxBxH: 46x16x2 [cm]<br \/><br \/>Netwerkkabels nodig? Kijk bij 'accessoires' voor FTP-producten.",
        "categorie": "toetsenborden",
        "type": "PS2",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "36.0000",
        "prijsperstuk": "6.0000",
        "verzendkosten": null,
        "bestelhoeveelheid": 6,
        "leverancier": "Nedis: CMP-KB22\/NL (7 stuks)",
        "picture": "~\/images\/CMP-22.JPG",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 179,
        "volgnummer": 100,
        "product": "HP-305 -  2 meter",
        "omschrijving": "Dit is de uitvoering met 2 meter snoer. <br \/>Er is ook de HP 305 - 1 meter met een korter snoer<br \/><br \/><br \/>Comfortabele multimedia hoofdtelefoon met lang snoer en draaibare oorschelpen.<br \/><br \/>Uitvoering met eenzijdig snoer van 1,8 meter lengte.<br \/><br \/><br \/>Ideaal als de computer op de grond staat door het lange snoer. Doordat het snoer aan één kant zit hangt dit niet voor het gezicht van de gebruiker.<br \/><br \/>Per stuk verpakt in een plastic zakje, dus geen overbodige blister.<br \/><br \/>Aansluiting: 3.5 mm plug <br \/>Kabellengte: 2  meter<br \/>Verpakking: per stuk in zakje, per 100 in doos<br \/><br \/>Download de PDF voor meer informatie ",
        "categorie": "hoofdtelefoons",
        "type": "comfort",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "99.5000",
        "prijsperstuk": "1.6500",
        "verzendkosten": null,
        "bestelhoeveelheid": 50,
        "leverancier": "Alto comfort (100 stuks)",
        "picture": "~\/images\/3052msite.png",
        "pdf": "~\/pdffiles\/HP 305.pdf",
        "prijs2": "175.0000",
        "bestelhoeveelheid2": 100,
        "prijs3": "330.0000",
        "bestelhoeveelheid3": 200,
        "Nieuw": null
    },
    {
        "id": 200,
        "volgnummer": 779,
        "product": "FTP kabel GR (1 meter)",
        "omschrijving": "Folie afgeschermde CAT5e FTP patch kabel.<br \/><br \/>Lengte: 1 meter<br \/>Kleur: Groen<br \/>",
        "categorie": "Netwerk kabels",
        "type": "FTP",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "5.8800",
        "prijsperstuk": "1.9600",
        "verzendkosten": null,
        "bestelhoeveelheid": 3,
        "leverancier": "Nedis: FTP-0007-1GR (3 stuks)",
        "picture": "~\/images\/FTPGROEN.JPG",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 201,
        "volgnummer": 779,
        "product": "FTP kabel RD (1 meter)",
        "omschrijving": "Folie afgeschermde CAT5e FTP patch kabel.<br \/><br \/>Lengte: 1 meter<br \/>Kleur: Rood<br \/>",
        "categorie": "Netwerk kabels",
        "type": "FTP",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "5.8800",
        "prijsperstuk": "1.9600",
        "verzendkosten": null,
        "bestelhoeveelheid": 3,
        "leverancier": "Nedis: FTP-0007-1RE (3 stuks)",
        "picture": "~\/images\/FTPROOD.JPG",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 202,
        "volgnummer": 779,
        "product": "FTP kabel GL (1 meter)",
        "omschrijving": "Folie afgeschermde CAT5e FTP patch kabel.<br \/><br \/>Lengte: 1 meter<br \/>Kleur: Geel<br \/>",
        "categorie": "Netwerk kabels",
        "type": "FTP",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "5.8800",
        "prijsperstuk": "1.9600",
        "verzendkosten": null,
        "bestelhoeveelheid": 3,
        "leverancier": "Nedis: FTP-0007-1YE (3 stuks)",
        "picture": "~\/images\/FTPGEEL.JPG",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 203,
        "volgnummer": 781,
        "product": "FTP koppelstuk",
        "omschrijving": "Modulair koppelstuk voor FTP-kabels.<br \/><br \/>Ideaal voor het snel verlengen van netwerkkabels.<br \/><br \/>",
        "categorie": "Netwerk kabels",
        "type": "FTP",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "4.9500",
        "prijsperstuk": "0.9900",
        "verzendkosten": null,
        "bestelhoeveelheid": 5,
        "leverancier": "Nedis: TEL-0008 8\/8B (5 stuks)",
        "picture": "~\/images\/TELCON88.JPG",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 210,
        "volgnummer": 145,
        "product": "Hoofdtelefoonsplitter",
        "omschrijving": "splitter om 2 hoofdtelefoons op 1 uitgang te kunnen aansluiten<br \/><br \/>Kabellengte 20 cm<br \/><br \/>",
        "categorie": "hoofdtelefoon accessoires",
        "type": "splitter",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "37.0000",
        "prijsperstuk": "1.8500",
        "verzendkosten": "9.0000",
        "bestelhoeveelheid": 20,
        "leverancier": "Nedis cable 415 (20 stuks)",
        "picture": "~\/images\/spl.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 211,
        "volgnummer": 142,
        "product": "6,3 - 3,5 mm adapter",
        "omschrijving": "Adapter om een 3,5 mm hoofdtelefoon te kunnen gebruiken op een 6,3 mm aansluiting<br \/><br \/>",
        "categorie": "hoofdtelefoon accessoires",
        "type": "adapter",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "20.0000",
        "prijsperstuk": "1.0000",
        "verzendkosten": "9.0000",
        "bestelhoeveelheid": 20,
        "leverancier": "nedis AC 007 (20 stuks)",
        "picture": "~\/images\/AC-007.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 227,
        "volgnummer": 215,
        "product": "Muismat Zwart",
        "omschrijving": "Neutrale muismat van 18x22 [cm].<br \/><br \/>",
        "categorie": "muismatten",
        "type": "zwart",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "19.0000",
        "prijsperstuk": "1.9000",
        "verzendkosten": null,
        "bestelhoeveelheid": 10,
        "leverancier": "Nedis: CMP-MAT3 (10 stuks)",
        "picture": "~\/images\/muismatzwartweb.jpg",
        "pdf": "~\/pdffiles\/muismatzwartweb.jpg",
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 231,
        "volgnummer": 768,
        "product": "Computerslot 3 m",
        "omschrijving": "Beveilig uw computerapparatuur tegen diefstal met dit kableslot.<br \/>Inclusief twee sleutels.<br \/>Lengte kabelslot: 3 meter.<br \/><br \/>Geschikt voor Kensington slotgaten welke tegenwoordig standaard in pc's, laptop's en beamers zitten.",
        "categorie": "accessoires",
        "type": "Sloten",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "21.9600",
        "prijsperstuk": "5.4900",
        "verzendkosten": null,
        "bestelhoeveelheid": 4,
        "leverancier": "Nedis: CMP-SAFE3\/3 (4 stuks)",
        "picture": "~\/images\/slot18.JPG",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 232,
        "volgnummer": 768,
        "product": "Combinatieslot computer",
        "omschrijving": "Beveilig uw computerapparatuur tegen diefstal met dit kableslot.<br \/>Door de gebruiker instelbaar combinatieslot met maximaal 10.000 instellingen voor optimale beveiliging. Geen sleutels nodig.<br \/><br \/>Lengte kabelslot: 1,8 meter.<br \/><br \/>Geschikt voor Kensington slotgaten welke tegenwoordig standaard in pc's, laptop's en beamers zitten.",
        "categorie": "accessoires",
        "type": "Sloten",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "27.8000",
        "prijsperstuk": "6.9500",
        "verzendkosten": null,
        "bestelhoeveelheid": 4,
        "leverancier": "Nedis: CMP-SAFE4 (4 stuks)",
        "picture": "~\/images\/slotCijfer.JPG",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 233,
        "volgnummer": 801,
        "product": "USB verlengkabel (5 meter)",
        "omschrijving": "Aktieve USB verlengkabel 5 meter<br \/><br \/>USB A male - USB A female met vergulde pluggen. <br \/><br \/>Als men een USB kabel wil verlengen over een grotere afstand, dan is het aan te raden hiervoor een actieve verlengkabel te gebruiken. Een actieve verlengkabel zorgt ervoor dat de signalen extra worden versterkt. <br \/>Hierdoor treden minder signaalverlies en storingen op <br \/><br \/>Grotere aantallen nodig? Stuur een email naar Info@Fetum.nl voor een passende aanbieding<br \/>",
        "categorie": "usb kabels",
        "type": "USB verleng",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "44.9500",
        "prijsperstuk": "8.9900",
        "verzendkosten": null,
        "bestelhoeveelheid": 5,
        "leverancier": "Cable-147HS (5 stuks)",
        "picture": "~\/images\/aktieveusb5mkabel.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 252,
        "volgnummer": 807,
        "product": "USB A-mini 5P 1.8",
        "omschrijving": "USB A naar B mini 5-polig.<br \/>Geschikt voor o.a. het aansluiten van digitale camera of externe geheugen.<br \/><br \/>Lengte van de kabel is 1,8 meter.<br \/><br \/>Grotere aantallen nodig? Stuur een email naar Info@Fetum.nl voor een passende aanbieding.",
        "categorie": "usb kabels",
        "type": "USB A-5P",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "6.1800",
        "prijsperstuk": "3.0900",
        "verzendkosten": null,
        "bestelhoeveelheid": 2,
        "leverancier": "Nedis: CABLE-161 (2 stuks)",
        "picture": "~\/images\/A 10011.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 253,
        "volgnummer": 809,
        "product": "USB A-mini 5P 5.0",
        "omschrijving": "USB A naar B mini 5-polig.<br \/>Geschikt voor o.a. het aansluiten van digitale camera of externe geheugen.<br \/><br \/>Lengte van de kabel is 5 meter.<br \/><br \/>Grotere aantallen nodig? Stuur een email naar Info@Fetum.nl voor een passende aanbieding.",
        "categorie": "usb kabels",
        "type": "USB A-5P",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "8.4400",
        "prijsperstuk": "4.2200",
        "verzendkosten": null,
        "bestelhoeveelheid": 2,
        "leverancier": "Nedis: CABLE-161\/5 (2 stuks)",
        "picture": "~\/images\/A 10011.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 254,
        "volgnummer": 804,
        "product": "USB A-B (1,8 meter)",
        "omschrijving": "USB kabel A naar B met een lengte van 1,8 meter.<br \/><br \/>Deze kabel wordt bijvoorbeeld gebruikt voor het aansluiten van een printer of scanner.<br \/><br \/>Grotere aantallen nodig? Stuur een email naar Info@Fetum.nl voor een passende aanbieding.",
        "categorie": "usb kabels",
        "type": "USB A-B",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "6.0200",
        "prijsperstuk": "3.0100",
        "verzendkosten": null,
        "bestelhoeveelheid": 2,
        "leverancier": "Nedis: CABLE-141HS (2 stuks)",
        "picture": "~\/images\/A10010.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 255,
        "volgnummer": 810,
        "product": "USB A-MicroA 1.8",
        "omschrijving": "USB kabel om bijvoorbeeld uw GSM of PDA met de computer te verbinden.<br \/><br \/>Let op! Ook de Micro B connector wordt veel gebruikt voor GSM en PDA, dus controleer goed welke u nodig heeft.<br \/><br \/>Pluggen: <br \/>USB A male<br \/>USB Micro A<br \/><br \/>Geschikt voor USB 2.0",
        "categorie": "usb kabels",
        "type": "USB A-micro",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "13.7700",
        "prijsperstuk": "4.5900",
        "verzendkosten": null,
        "bestelhoeveelheid": 3,
        "leverancier": "Nedis: CABLE-166-1.8 ( 3 stuks)",
        "picture": "~\/images\/CABLEAmicro.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 256,
        "volgnummer": 811,
        "product": "USB A-MicroB 1.8",
        "omschrijving": "USB kabel om bijvoorbeeld uw GSM of PDA met de computer te verbinden.<br \/><br \/>Let op! Ook de Micro A connector wordt veel gebruikt voor GSM en PDA, dus controleer goed welke u nodig heeft.<br \/><br \/>Pluggen: <br \/>USB A male<br \/>USB Micro B<br \/><br \/>Geschikt voor USB 2.0",
        "categorie": "usb kabels",
        "type": "USB A-micro",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "8.9000",
        "prijsperstuk": "4.4500",
        "verzendkosten": null,
        "bestelhoeveelheid": 2,
        "leverancier": "Nedis: CABLE-167-1.8 (2 stuks)",
        "picture": "~\/images\/CABLEAmicroB.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 257,
        "volgnummer": 771,
        "product": "Monitor kabel 5.0",
        "omschrijving": "Dubbel afgeschermde hoge kwaliteits kabel om een monitor aan te sluiten op de computer.<br \/><br \/>Lengte kabel: 5 meter<br \/>Type connector: VGA male \/ VGA male<br \/><br \/>Langere kabels nodig? Stuur een email naar Info@Fetum.nl voor een vrijblijvende prijsopgave.",
        "categorie": "accessoires",
        "type": "Monitor",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "38.3000",
        "prijsperstuk": "7.6600",
        "verzendkosten": null,
        "bestelhoeveelheid": 5,
        "leverancier": "Nedis: CABLE-177\/5 (5 stuks)",
        "picture": "~\/images\/MonitorHE.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 258,
        "volgnummer": 770,
        "product": "Monitor kabel 3.0",
        "omschrijving": "Dubbel afgeschermde hoge kwaliteits kabel om een monitor aan te sluiten op de computer.<br \/><br \/>Lengte kabel: 3 meter.<br \/>Type connector: VGA male \/ VGA male.<br \/>",
        "categorie": "accessoires",
        "type": "Monitor",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "36.6000",
        "prijsperstuk": "7.3200",
        "verzendkosten": null,
        "bestelhoeveelheid": 5,
        "leverancier": "Nedis:  CABLE177\/3 (5 stuks)",
        "picture": "~\/images\/MonitorHE.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 267,
        "volgnummer": 785,
        "product": "Wireless Access point",
        "omschrijving": "Sluit het Wireless Access point eenvoudig aan op een bekabeld netwerk en er is een draadloze verbinding.<br \/><br \/>Snel en eenvoudig een draadloos netwerk!<br \/><br \/>Voldoet aan IEEE 802.11g en b standaarden.<br \/>Beveiliging: WEP & WPA encryptie.<br \/>Snelheid: 54 Mbps<br \/>Ondersteunt AP\/AP Client\/Bridge\/Multi-Bridge mode en WDS.<br \/>Afneembare SMA connector antenne.",
        "categorie": "computer netwerk",
        "type": "Acces point",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "33.9900",
        "prijsperstuk": "33.9900",
        "verzendkosten": null,
        "bestelhoeveelheid": 1,
        "leverancier": "Nedis: CMP-WNAP20 (1 stuks)",
        "picture": "~\/images\/WNP10.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 281,
        "volgnummer": 415,
        "product": "LG afstandsbediening",
        "omschrijving": "Vervangings afstandsbediening voor LG tv's.",
        "categorie": "afstandsbedieningen",
        "type": null,
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "89.7500",
        "prijsperstuk": "17.9500",
        "verzendkosten": null,
        "bestelhoeveelheid": 5,
        "leverancier": "Nedis: RC SMARTHOTEL (5 stuks)",
        "picture": "~\/images\/RC_SMARTHotel.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 293,
        "volgnummer": 85,
        "product": "HP-2705 volumeregeling",
        "omschrijving": "Hoofdtelefoon met volumeregeling<br \/><br \/>De hoofdtelefoons hebben ca. 2 meter snoer met daarin opgenomen een volumeregeling.<br \/><br \/>Kleur: zwart.<br \/>lengte snoer: ca. 2 meter<br \/>aansluiting: 3,5 mm stereo stekker.<br \/>verpakking: per 125 stuks in doos.<br \/><br \/>Download de PDF voor meer informatie ",
        "categorie": "hoofdtelefoons",
        "type": "budget",
        "eigenschap": "volumeregeling",
        "groep": "winkelier",
        "prijs": "186.2500",
        "prijsperstuk": "1.3900",
        "verzendkosten": null,
        "bestelhoeveelheid": 125,
        "leverancier": "Alto AHS LR",
        "picture": "~\/images\/2705 LG geel block.jpg",
        "pdf": "~\/pdffiles\/HP 2705 LR.pdf",
        "prijs2": "347.5000",
        "bestelhoeveelheid2": 250,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 295,
        "volgnummer": 106,
        "product": "Hoofdtelefoonkussentjes 302",
        "omschrijving": "Vervangende kussentjes voor de HP-302 hoofdtelefoon.<br \/><br \/>Per set (2 stuks) verpakt in een zakje, per 100 sets in een overdoos.",
        "categorie": "hoofdtelefoons",
        "type": "kussentjes",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "49.0000",
        "prijsperstuk": "0.4900",
        "verzendkosten": "4.9500",
        "bestelhoeveelheid": 100,
        "leverancier": "alto",
        "picture": "~\/images\/kussentjes302web.jpg",
        "pdf": "~\/pdffiles\/kussentjes.pdf",
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 296,
        "volgnummer": 32,
        "product": "CR2025 Lithium 3V",
        "omschrijving": "Voltage: 3V<br \/>afmetingen: 20x 2,5 mm",
        "categorie": "batterijen",
        "type": "Knoopcel",
        "eigenschap": null,
        "groep": "Winkelier",
        "prijs": "4.7500",
        "prijsperstuk": "0.9500",
        "verzendkosten": null,
        "bestelhoeveelheid": 5,
        "leverancier": "Nedis: CR2025(5 stuks)",
        "picture": "~\/images\/CR2025.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 298,
        "volgnummer": 7,
        "product": "HQ AAA Alkaline",
        "omschrijving": "Goede alkaline batterijen voor algemeen gebruik. <br \/><br \/>Per 2 stuks in een folie verpakt. Neemt weinig ruimte in en geeft weinig afval. <br \/><br \/>Lang houdbaar.<br \/><br \/><br \/><br \/>De verplichte Verwijderingsbijdrage is in de totaalprijs opgenomen (0,02 per batterij).<br \/><br \/>",
        "categorie": "batterijen",
        "type": "AAA",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "30.7200",
        "prijsperstuk": "0.2100",
        "verzendkosten": null,
        "bestelhoeveelheid": 96,
        "leverancier": "HQ-ALK-AA-03",
        "picture": "~\/images\/AAAalkaline2.jpg",
        "pdf": null,
        "prijs2": "60.0000",
        "bestelhoeveelheid2": 240,
        "prijs3": "201.6000",
        "bestelhoeveelheid3": 960,
        "Nieuw": null
    },
    {
        "id": 305,
        "volgnummer": 551,
        "product": "LCD muurbeugel draai- en kantelbaar",
        "omschrijving": "Muurbeugel voor LCD schermen van 10 tot 26 inch met een maximale gewicht van 20 kg. De beugel is draaibaar (op  2 punten) en kantelbaar en dit biedt daardoor veel flexibiliteit in de positie van het scherm. <br \/><br \/>De kabels kunnen opgeborden worden in de beugelarm.<br \/><br \/>Draaibaar: 180 graden<br \/>Kantelbaar: 20 graden<br \/>Zwenkbaar: 180 graden<br \/>VESA: 50 \/ 75 \/ 100 \/ 100 x 200 <br \/>Kleur: zilver",
        "categorie": "TV beugel",
        "type": "Draai en kantelbaar",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "31.0000",
        "prijsperstuk": "27.0000",
        "verzendkosten": null,
        "bestelhoeveelheid": 1,
        "leverancier": "NEDIS: TVS-LCD21",
        "picture": "~\/images\/21webafbeelding.jpg",
        "pdf": "~\/pdffiles\/Draaikantelbeugel 26 inch zilver 21.pdf",
        "prijs2": "29.0000",
        "bestelhoeveelheid2": 5,
        "prijs3": "27.0000",
        "bestelhoeveelheid3": 10,
        "Nieuw": null
    },
    {
        "id": 306,
        "volgnummer": 511,
        "product": "Vaste muurbeugel",
        "omschrijving": "Vaste muurbeugel voor 22 tot 37 inch LCD's. Met deze beugel kan het scherm dicht tegen de muur komen te hangen.<br \/><br \/>Maximale gewicht: 45 kg<br \/>Kleur: zilver<br \/>Draaibaar: nee<br \/>Kantelbaar: nee",
        "categorie": "TV beugel",
        "type": "Vaste bevestiging",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "29.0000",
        "prijsperstuk": "25.0000",
        "verzendkosten": null,
        "bestelhoeveelheid": 1,
        "leverancier": "NEDIS: TVS-LCD610\/HQ",
        "picture": "~\/images\/26-37inch vastebeugel website.jpg",
        "pdf": "~\/pdffiles\/26-37 inch kantelbeugel.pdf",
        "prijs2": "27.0000",
        "bestelhoeveelheid2": 5,
        "prijs3": "25.0000",
        "bestelhoeveelheid3": 10,
        "Nieuw": null
    },
    {
        "id": 307,
        "volgnummer": 512,
        "product": "Vaste muurbeugel met anti diefstalsysteem",
        "omschrijving": "Vaste muurbeugel voor 23 tot 37 inch LCD's. De snap safety lock beschremd de TV tegen vallen. Daarnaast beschikt de beugel over een anti diefstalsysteem.<br \/><br \/>Maximale gewicht: 40 kg<br \/>Kleur: zwart<br \/>Draaibaar: nee<br \/>Kantelbaar: 15 graden<br \/>Vesa: 100\/200\/200x100",
        "categorie": "TV beugel",
        "type": "Vaste bevestiging",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "56.0000",
        "prijsperstuk": "56.0000",
        "verzendkosten": null,
        "bestelhoeveelheid": 1,
        "leverancier": "NEDIS: TVS-KN-FSB-115B",
        "picture": "~\/images\/TVS-KN-FSB115B.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 308,
        "volgnummer": 503,
        "product": "Vaste muurbeugel",
        "omschrijving": "Vaste muurbeugel voor 14 tot 32 inch LCD's. Met deze beugel kan het scherm zeer dicht tegen de muur kom te hangen.<br \/><br \/>Maximale gewicht: 20 kg<br \/>Kleur: Zwart<br \/>Draaibaar: Nee<br \/>Kantelbaar: Nee<br \/>Vesa: 50\/75\/100\/200\/100x200<br \/><br \/><br \/><br \/><br \/>",
        "categorie": "TV beugel",
        "type": "Vaste bevestiging",
        "eigenschap": null,
        "groep": "Winkelier",
        "prijs": "15.0000",
        "prijsperstuk": "11.0000",
        "verzendkosten": null,
        "bestelhoeveelheid": 1,
        "leverancier": "NEDIS: TVS-LCD801B-HQ",
        "picture": "~\/images\/TVS-LCD801B-HQ.jpg",
        "pdf": "~\/pdffiles\/19-32 inch vast.pdf",
        "prijs2": "13.0000",
        "bestelhoeveelheid2": 5,
        "prijs3": "11.0000",
        "bestelhoeveelheid3": 10,
        "Nieuw": null
    },
    {
        "id": 313,
        "volgnummer": 517,
        "product": "Kantelbare muurbeugel zilver",
        "omschrijving": "Kantelbare muurbeugel voor 26 inch LCD's. <br \/><br \/>Het toestel hangt dicht tegen de muur, maar kan iets naar vorgen gekanteld worden om het kijken nog aangenamer te maken.<br \/><br \/>Maximale gewicht: 45 kg<br \/>Kleur: zilver<br \/>Draaibaar: nee<br \/>Kantelbaar: 15 graden<br \/>Vesa: universeel ",
        "categorie": "TV beugel",
        "type": "Kantelbare muurbeugel",
        "eigenschap": null,
        "groep": "Winkelier",
        "prijs": "31.0000",
        "prijsperstuk": "26.0000",
        "verzendkosten": null,
        "bestelhoeveelheid": 1,
        "leverancier": "NEDIS: TVS-LCD710\/HQ",
        "picture": "~\/images\/kantelbarebeugel 26-37 inch.jpg",
        "pdf": "~\/pdffiles\/26-37 inch kantelbeugel.pdf",
        "prijs2": "29.0000",
        "bestelhoeveelheid2": 5,
        "prijs3": "26.0000",
        "bestelhoeveelheid3": 10,
        "Nieuw": null
    },
    {
        "id": 314,
        "volgnummer": 572,
        "product": "Instelbare beamer plafondbeugel",
        "omschrijving": "Plafondbeugel voor projectoren en beamers.<br \/>Universeel ontwerp past met alle populaire merken <br \/><br \/>Specificaties: <br \/>Max. gewicht: 11 kg <br \/>Minimale afstand tot plafond: 56,5 cm<br \/>Maximale afstand tot plafond: 81,5 cm <br \/>Kleur: Zilver <br \/>Draaibaar: Ja<br \/><br \/>Voor meer informatie over beugels kunt u een email sturen naar Info@Fetum.nl.<br \/>",
        "categorie": "Beamer beugel",
        "type": "beamer",
        "eigenschap": null,
        "groep": "Winkelier",
        "prijs": "74.0000",
        "prijsperstuk": "74.0000",
        "verzendkosten": null,
        "bestelhoeveelheid": 1,
        "leverancier": "NEDIS: TVS-MOD91\/BA",
        "picture": "~\/images\/TVS-MOD91_BA.jpg",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 317,
        "volgnummer": 13,
        "product": "HQ C Alkaline",
        "omschrijving": "D-alkaline batterijen (LR14) per twee stuks in blister. Bestelhoeveelheid is 12 stuks.<br \/><br \/>Hoogte: 49,5 mm.<br \/>Diameter: 25,5 mm.<br \/>Voltage:1,5 V<br \/><br \/>De verplichte Verwijderingsbijdrage is in de prijs opgenomen (0,02 per batterij).<br \/><br \/>Andere aantallen nodig? Mail voor een aanbieding op maat naar Info@Fetum.nl. ",
        "categorie": "batterijen",
        "type": "C",
        "eigenschap": null,
        "groep": "Winkelier",
        "prijs": "13.4400",
        "prijsperstuk": "1.1000",
        "verzendkosten": null,
        "bestelhoeveelheid": 12,
        "leverancier": "NEDIS: HQ-LR14",
        "picture": "~\/images\/Batsite.png",
        "pdf": null,
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 323,
        "volgnummer": 900,
        "product": "Webcam 2",
        "omschrijving": "Degelijke eenvoudig te gebruiken webcam<br \/><br \/>Een compacte webcam die neergezet kan worden of vastgeknepen (bijvoorbeeld op een monitor). De constructie is zeer degelijk.<br \/>De webcam is geschikt en te gebruiken door ierereen.<br \/><br \/>Voorzien van 3 LED's (handmatig in te schakelen) en daardoor ook bij weinig licht goed te gebruiken.<br \/><br \/>De webcam beschikt over een USB aansluiting en is plug and play.<br \/>Geschikt voor: Windows XP, Vista en 7",
        "categorie": "webcam",
        "type": "webcam",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "39.7500",
        "prijsperstuk": "7.9500",
        "verzendkosten": null,
        "bestelhoeveelheid": 5,
        "leverancier": "Nedis BXL-Webcam2bl",
        "picture": "~\/images\/webcamopmonitor.jpg",
        "pdf": "~\/pdffiles\/Webcam2.pdf",
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 324,
        "volgnummer": 783,
        "product": "Switch SW5",
        "omschrijving": "Met deze compact Switch kan een netwerk snel met 4 extra pc's of switches worden uitgebreid.<br \/><br \/>Elke netwerkpoort van deze Switch is geschikt als uplink-poort, wat inhoudt dat er gemakkelijk andere switches aangesloten kunnen worden om het netwerk nog verder uit te breiden.<br \/><br \/>Snelheid: 10\/100 Mbps<br \/><br \/>De switch is plug-and play, er hoeft geen software geinstalleerd te worden.",
        "categorie": "computer netwerk",
        "type": "switch",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "17.0000",
        "prijsperstuk": "17.0000",
        "verzendkosten": null,
        "bestelhoeveelheid": 1,
        "leverancier": "Nedis CMP-EHUB15",
        "picture": "~\/images\/switch5site.jpg",
        "pdf": null,
        "prijs2": "75.0000",
        "bestelhoeveelheid2": 5,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 334,
        "volgnummer": 125,
        "product": "HP-32",
        "omschrijving": "Flexibel In-ear oorje in bewaardoosje met doorzichtig dekseltje.  .<br \/><br \/>Wordt in het oor gedragen en sluit daardoor omgevingsgeluid goed buiten. Valt ook niet snel uit het oor.<br \/><br \/>Inclusief bewaardoosje. Ideaal om de oortjes na gebruik te bewaren en voorkomt dat het een rommeltje wordt.<br \/><br \/>Op het doosje kan de naam van de gebruiker met stift worden geschreven.<br \/><br \/>Wordt verkocht in verpakkingen van 50 stuks. <br \/>U ontvangt 50 stuks van dezelfde kleur. Het blijft een verrassing welke kleur! Maar er zijn geen ROZE doosjes meer.<br \/><br \/>download de PDF voor meer info",
        "categorie": "oortjes",
        "type": "in ear",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "82.5000",
        "prijsperstuk": "1.2900",
        "verzendkosten": "4.9500",
        "bestelhoeveelheid": 50,
        "leverancier": "GT",
        "picture": "~\/images\/HP32rood.jpg",
        "pdf": "~\/pdffiles\/HP-32N2209.pdf",
        "prijs2": "152.0000",
        "bestelhoeveelheid2": 100,
        "prijs3": "258.0000",
        "bestelhoeveelheid3": 200,
        "Nieuw": null
    },
    {
        "id": 335,
        "volgnummer": 104,
        "product": "HP-316 ultra sound",
        "omschrijving": "Ultra sound hoofdtelefoon<br \/><br \/>Multimedia hoofdtelefoon met draaibare oorschelpen.<br \/><br \/>Deze hoofdtelefoon heeft voor deze prijsklasse een ongekend goede geluidskwaliteit. Uitstekend geschikt voor muziek weergave.<br \/><br \/>De oorschelpen kunnen gedraaid worden. Dit is erg comfortabel. Met 2 meter eenzijdig snoer, dus het snoer komt uit een oorschelp.<br \/><br \/>Onze beste budget hoofdtelefoon<br \/><br \/>Download de pdf voor meer info",
        "categorie": "hoofdtelefoons",
        "type": "comfort",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "149.5000",
        "prijsperstuk": "2.6900",
        "verzendkosten": null,
        "bestelhoeveelheid": 50,
        "leverancier": "ALTO",
        "picture": "~\/images\/316 geel block 1303.jpg",
        "pdf": "~\/pdffiles\/HP 316.pdf",
        "prijs2": "279.0000",
        "bestelhoeveelheid2": 100,
        "prijs3": "538.0000",
        "bestelhoeveelheid3": 200,
        "Nieuw": null
    },
    {
        "id": 336,
        "volgnummer": 95,
        "product": "HP-2710",
        "omschrijving": "Leuke gekleurde hoofdtelefoon.<br \/>Kunststof hoofdtelefoon met gekleurde verstelbare hoofdband.<br \/><br \/>Bij 125 stuks bevat de oververpakking van alle vier de kleuren 31 stuks en één extra zwarte.<br \/><br \/>Bij 24 stuks treft u van ieder kleur 6 stuks in de doos.<br \/><br \/>Breng wat kleur in de klas met deze vrolijke hoofdtelefoon.<br \/><br \/><br \/>Per stuk verpakt en met een 180 cm lang zwart snoer en rechte stekker.<br \/><br \/>Download de PDF voor meer info",
        "categorie": "hoofdtelefoons",
        "type": "budget",
        "eigenschap": "gekleurd",
        "groep": "winkelier",
        "prijs": "46.8000",
        "prijsperstuk": "1.1500",
        "verzendkosten": null,
        "bestelhoeveelheid": 24,
        "leverancier": "1020",
        "picture": "~\/images\/2706 en 2710 frontweb.jpg",
        "pdf": "~\/pdffiles\/HP-2710.pdf",
        "prijs2": "156.2500",
        "bestelhoeveelheid2": 125,
        "prijs3": "287.5000",
        "bestelhoeveelheid3": 250,
        "Nieuw": null
    },
    {
        "id": 337,
        "volgnummer": 80,
        "product": "HP-2706",
        "omschrijving": "Volledig kunststof hoofdtelefoon.<br \/><br \/>Met 1.8 meter snoer en zelf stellende oorschelpen. Ook goed te gebruiken bij kleinere hoofdjes.<br \/><br \/>Per stuk ingeseald, per 250 in een overdoos.<br \/><br \/>Ideaal waar veel hoofdtelefoons worden gebruikt. <br \/><br \/><br \/>Een volledig kunststof uitvoering van deze populaire hoofdtelefoon. <br \/><br \/>Ook verkrijgbaar ik vrolijke kleurtjes, zie de HP 2710<br \/><br \/>Kleur: zwart<br \/>lengte snoer: ca 1,8 meter<br \/>aansluiting: 3,5 mm stereo stekker<br \/><br \/>Download de PDF voor meer informatie<br \/>",
        "categorie": "hoofdtelefoons",
        "type": "budget",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "131.2500",
        "prijsperstuk": "0.9500",
        "verzendkosten": null,
        "bestelhoeveelheid": 125,
        "leverancier": "alto 1030",
        "picture": "~\/images\/2706 met geel block.jpg",
        "pdf": "~\/pdffiles\/2706.pdf",
        "prijs2": "237.5000",
        "bestelhoeveelheid2": 250,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 338,
        "volgnummer": 82,
        "product": "HP-2707",
        "omschrijving": "Volledig kunststof hoofdtelefoon met lekker lang snoer van maar liefst drie meter! Heerlijk in het gebruik.<br \/><br \/>Per stuk ingeseald, per 250 in een overdoos.<br \/><br \/>Ideaal waar veel hoofdtelefoons worden gebruikt <br \/><br \/><br \/>Kleur: zwart<br \/>lengte snoer: 3 meter<br \/>aansluiting: 3,5 mm stereo stekker<br \/><br \/>Download de PDF voor meer informatie",
        "categorie": "hoofdtelefoons",
        "type": "budget",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "161.2500",
        "prijsperstuk": "1.1900",
        "verzendkosten": "4.9500",
        "bestelhoeveelheid": 125,
        "leverancier": "alto 1036",
        "picture": "~\/images\/2707 geel block.jpg",
        "pdf": "~\/pdffiles\/HP 2707.pdf",
        "prijs2": "297.5000",
        "bestelhoeveelheid2": 250,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    },
    {
        "id": 352,
        "volgnummer": 102,
        "product": "HP-112",
        "omschrijving": "Basis multimedia hoofdtelefoon met kort snoer, <br \/>grote vaste oorschelpen en stalen hoofdbeugel.<br \/><br \/>Kort snoer van 1,2 meter (goed geschikt voor tablets en chromebooks) met haakse stekker.<br \/><br \/>Een van onze oudgedienden. Al jaren populair en nu met de opkomst van de chromebooks aan een tweede carriere begonnen<br \/><br \/>Aansluiting: 3.5 mm haakse stekker <br \/>Kabellengte: 1,2 meter<br \/><br \/><br \/>Download de PDF voor meer informatie ",
        "categorie": "hoofdtelefoons",
        "type": "comfort",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "184.9600",
        "prijsperstuk": "5.1800",
        "verzendkosten": "4.9500",
        "bestelhoeveelheid": 32,
        "leverancier": "Nedis HP-112",
        "picture": "~\/images\/hp-122-web-insta.jpg",
        "pdf": "~\/pdffiles\/HP-112.pdf",
        "prijs2": "357.1200",
        "bestelhoeveelheid2": 64,
        "prijs3": "663.0400",
        "bestelhoeveelheid3": 128,
        "Nieuw": null
    },
    {
        "id": 355,
        "volgnummer": 122,
        "product": "I-889",
        "omschrijving": "Modern in-ear oortje met 1,2 meter  snoer.<br \/><br \/>Oortje en snoer in wit, kapjes is 4 verschillende kleuren (met ster)<br \/><br \/>Te gebruiken met: Telefoon, tablet, I-pad en chromebook<br \/><br \/>Dit oortje heeft geen microfoon<br \/><br \/>Per stuk verpakt in een zakje, per 100 in een overdoos",
        "categorie": "oortjes",
        "type": "in ear",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "64.8000",
        "prijsperstuk": "1.0900",
        "verzendkosten": "4.9500",
        "bestelhoeveelheid": 48,
        "leverancier": "Top Ten",
        "picture": "~\/images\/websiteii889.png",
        "pdf": "~\/pdffiles\/i-888.pdf",
        "prijs2": "114.2400",
        "bestelhoeveelheid2": 96,
        "prijs3": "209.2800",
        "bestelhoeveelheid3": 192,
        "Nieuw": null
    },
    {
        "id": 361,
        "volgnummer": 118,
        "product": "HP-88",
        "omschrijving": "Wiite hoofdtelefoon met opklapbare oorschelpen en uitstekende geluidskwaliteit<br \/><br \/>De Hoofdtelefoon beschikt over grote verstelbare oorschelpen en een flexibele hoofdband, wat gebruik bij grote en kleine hoofdjes goed mogelijk maakt.<br \/><br \/>Kleur: wit<br \/>Snoerlengte: 1,2 meter<br \/>Aansluiting: 3,5mm rechte stereo stekker<br \/>Verpakking: per stuk in blister, per 16 in overdoos<br \/><br \/>Download de PDF voor meer infomatie",
        "categorie": "hoofdtelefoons",
        "type": "degelijk",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "148.4800",
        "prijsperstuk": "8.0200",
        "verzendkosten": "4.9500",
        "bestelhoeveelheid": 16,
        "leverancier": "Nedis",
        "picture": "~\/images\/hp88site.png",
        "pdf": "~\/pdffiles\/HP-88W.pdf",
        "prijs2": "263.0400",
        "bestelhoeveelheid2": 32,
        "prijs3": "513.2800",
        "bestelhoeveelheid3": 64,
        "Nieuw": null
    },
    {
        "id": 363,
        "volgnummer": 130,
        "product": "i-44",
        "omschrijving": "In-ear oortje met ingebouwde microfoon, pauze toets in het snoer en een platte kabel<br \/><br \/>Te gebruiken met telefoon, tablet, i-Pad of chromebook.<br \/><br \/>Per verpakking 4 kleuren: <br \/>- wit<br \/>- rood<br \/>- blauw<br \/>- zwart<br \/><br \/>download de pdf voor alle informatie",
        "categorie": "oortjes",
        "type": "in ear",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "57.3600",
        "prijsperstuk": "1.8900",
        "verzendkosten": "4.9500",
        "bestelhoeveelheid": 24,
        "leverancier": "brahama",
        "picture": "~\/images\/i44website.png",
        "pdf": "~\/pdffiles\/i-44.pdf",
        "prijs2": "95.5200",
        "bestelhoeveelheid2": 48,
        "prijs3": "181.4400",
        "bestelhoeveelheid3": 96,
        "Nieuw": null
    },
    {
        "id": 364,
        "volgnummer": 101,
        "product": "HP-305 -  1 meter",
        "omschrijving": "Dit is de uitvoering met 1 meter snoer. <br \/>Er is ook de HP 305 - 2 meter met een langer snoer<br \/><br \/><br \/>Comfortabele multimedia hoofdtelefoon met eenzijdig snoer en draaibare oorschelpen.<br \/><br \/><br \/>Per stuk verpakt in een plastic zakje, dus geen overbodige blister.<br \/><br \/>Aansluiting: 3.5 mm plug <br \/>Kabellengte: 2  meter<br \/>Verpakking: per stuk in zakje, per 100 in doos<br \/><br \/>Download de PDF voor meer informatie ",
        "categorie": "hoofdtelefoons",
        "type": "comfort",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "99.5000",
        "prijsperstuk": "1.6500",
        "verzendkosten": "4.9500",
        "bestelhoeveelheid": 50,
        "leverancier": "Alto comfort (100 stuks)",
        "picture": "~\/images\/3051msite.png",
        "pdf": "~\/pdffiles\/HP 305.pdf",
        "prijs2": "175.0000",
        "bestelhoeveelheid2": 100,
        "prijs3": "330.0000",
        "bestelhoeveelheid3": 200,
        "Nieuw": null
    },
    {
        "id": 365,
        "volgnummer": 122,
        "product": "HP-122 N",
        "omschrijving": "Unieke nekband hoofdtelefoon<br \/><br \/>Geschikt voor grote en kleinere gebruikers. <br \/><br \/>Met 1,2 meter snoer en zachte oorschelpen. Voorzien van een verstevigd snoer aan één kant van de hoofdtelefoon.<br \/><br \/>Per stuk verpakt in een opruimtas.<br \/><br \/><br \/><br \/>Download de PDF voor meer info.<br \/>",
        "categorie": "hoofdtelefoons",
        "type": "nekband",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "186.5600",
        "prijsperstuk": "5.2300",
        "verzendkosten": "4.9500",
        "bestelhoeveelheid": 32,
        "leverancier": "Nedis",
        "picture": "~\/images\/122 met hoofd in oranje.jpg",
        "pdf": "~\/pdffiles\/HP-122N.pdf",
        "prijs2": "360.3200",
        "bestelhoeveelheid2": 64,
        "prijs3": "669.4400",
        "bestelhoeveelheid3": 128,
        "Nieuw": null
    },
    {
        "id": 366,
        "volgnummer": 200,
        "product": "BT - 7",
        "omschrijving": "Degelijke witte bluetooth hoofdtelefoon.<br \/><br \/>Inklapbaar (makkelijk op te ruimen), voorzien van rubberen oorschelpen (eenvoudig schoon te houden).<br \/><br \/>Kan na opladen zo'n 3 a 4 uur gebruikt worden. En is de batterij leeg dan is de bijgeleverde hoofdtelefoon kabel handig voor noodgevallen.<br \/><br \/>Beschikt ook over een microfoon.<br \/><br \/>Is te gebruiken met alle apparaten (tablet, telefoon, Chromebook, pc) die voorzien zijn van BT. Wordt geleverd met USB-oplaadkabel.<br \/><br \/>Bij gebruik van meerdere apparaten tegelijk storen ze elkaar niet.<br \/><br \/>Download de PDF voor alle details",
        "categorie": "hoofdtelefoons",
        "type": "bluetooth",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "94.0000",
        "prijsperstuk": "14.8000",
        "verzendkosten": "4.9500",
        "bestelhoeveelheid": 5,
        "leverancier": "Anda",
        "picture": "~\/images\/bt7site.jpg",
        "pdf": "~\/pdffiles\/BT7.pdf",
        "prijs2": "168.0000",
        "bestelhoeveelheid2": 10,
        "prijs3": "296.0000",
        "bestelhoeveelheid3": 20,
        "Nieuw": null
    },
    {
        "id": 367,
        "volgnummer": 119,
        "product": "HP-188",
        "omschrijving": "Blauwe inklapbare comfortabele hoofdtelefoon. <br \/><br \/>Flexibele met zacht stof beklede hoofdband, verstelbare oorschelpen en enkelzijdig verstevigd snoer.<br \/><br \/>Uitgevoerd in een neutrale blauwe kleur. De speakers zijn inklapbaar zodat de hoofdtelefoon bij opruimen weinig plaats inneemt.<br \/><br \/>Voorzien van een met stof omkleed snoer en compacte stekker.<br \/><br \/>Per stuk verpakt in een kartonnen doosje.<br \/><br \/>Download de PDF voor meer info.<br \/>",
        "categorie": "hoofdtelefoons",
        "type": "degelijk",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "157.8000",
        "prijsperstuk": "6.2900",
        "verzendkosten": "4.9500",
        "bestelhoeveelheid": 20,
        "leverancier": "anda",
        "picture": "~\/images\/hp-188 site.jpg",
        "pdf": "~\/pdffiles\/HP-188.pdf",
        "prijs2": "283.6000",
        "bestelhoeveelheid2": 40,
        "prijs3": "503.2000",
        "bestelhoeveelheid3": 80,
        "Nieuw": null
    },
    {
        "id": 370,
        "volgnummer": 202,
        "product": "BT - 88",
        "omschrijving": "Elegante en stevige bluetooth hoofdtelefoon<br \/><br \/>De speakers zijn in te klappen en in hoogte verstelbaar. <br \/><br \/>Kan na opladen zo'n 5 a 6 uur gebruikt worden. En is de batterij leeg dan is de bijgeleverde hoofdtelefoon kabel handig voor noodgevallen.<br \/><br \/>Is te gebruiken met alle apparaten (tablet, telefoon, Chromebook, pc) die voorzien zijn van BT. Wordt geleverd met USB-oplaadkabel.<br \/><br \/>Bij gebruik van meerdere apparaten tegelijk storen ze elkaar niet.<br \/><br \/>Download de PDF voor alle details",
        "categorie": "hoofdtelefoons",
        "type": "bluetooth",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "104.0000",
        "prijsperstuk": "16.8000",
        "verzendkosten": "4.9500",
        "bestelhoeveelheid": 5,
        "leverancier": "Nedis",
        "picture": "~\/images\/BT 88 web.jpg",
        "pdf": "~\/pdffiles\/BT - 88.pdf",
        "prijs2": "188.0000",
        "bestelhoeveelheid2": 10,
        "prijs3": "336.0000",
        "bestelhoeveelheid3": 20,
        "Nieuw": null
    },
    {
        "id": 371,
        "volgnummer": 127,
        "product": "i-40",
        "omschrijving": "Stijlvol wit oortje met volume regeling en pauze knop<br \/><br \/>Leverbaar met (i-40 N) en zonder doosje (i-40)<br \/><br \/>DIT IS DE UITVOERING ZONDER DOOSJE<br \/><br \/>1 meter snoer, goede geluidskwaliteit en langdurig te gebruiken.",
        "categorie": "oortjes",
        "type": "in ear",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "129.1200",
        "prijsperstuk": "2.3800",
        "verzendkosten": "4.9500",
        "bestelhoeveelheid": 48,
        "leverancier": "Bahama",
        "picture": "~\/images\/i-40 site.jpg",
        "pdf": "~\/pdffiles\/i-40 (N).pdf",
        "prijs2": "248.6400",
        "bestelhoeveelheid2": 96,
        "prijs3": "456.9600",
        "bestelhoeveelheid3": 192,
        "Nieuw": null
    },
    {
        "id": 372,
        "volgnummer": 128,
        "product": "i-40 N",
        "omschrijving": "Stijlvol wit oortje met volume regeling en pauze knop<br \/><br \/>Leverbaar met (i-40 N) en zonder doosje (i-40)<br \/><br \/>DIT IS DE UITVOERING MET DOOSJE<br \/><br \/>1 meter snoer, goede geluidskwaliteit en langdurig te gebruiken.",
        "categorie": "oortjes",
        "type": "in ear",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "177.1200",
        "prijsperstuk": "3.2800",
        "verzendkosten": "4.9500",
        "bestelhoeveelheid": 48,
        "leverancier": "Bahama ANDA",
        "picture": "~\/images\/i40 N.jpg",
        "pdf": "~\/pdffiles\/i-40 (N).pdf",
        "prijs2": "355.0400",
        "bestelhoeveelheid2": 96,
        "prijs3": "629.7600",
        "bestelhoeveelheid3": 192,
        "Nieuw": null
    },
    {
        "id": 373,
        "volgnummer": 207,
        "product": "Draadloze Muis 155 rood",
        "omschrijving": "Platte draadloze muis met scrollweel. Leverbaar in drie vrolijke kleuren. Dit is de RODE uitvoering.<br \/><br \/>Scrollweel dient ook als middelse muisknop.<br \/>Inclusief dongle (te bewaren in de muis) en 2 Alkaline batterijen. Dus direct klaar voor gebruik. Geen software te installeren.<br \/><br \/>Werkt met Chromebook, Apple en windows pc.<br \/><br \/>Download de PDF voor meer info",
        "categorie": "muizen",
        "type": "draadloos",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "132.6000",
        "prijsperstuk": "5.6900",
        "verzendkosten": null,
        "bestelhoeveelheid": 20,
        "leverancier": "anda",
        "picture": "~\/images\/rood.jpg",
        "pdf": "~\/pdffiles\/Muis155c.pdf",
        "prijs2": "240.8000",
        "bestelhoeveelheid2": 40,
        "prijs3": "455.2000",
        "bestelhoeveelheid3": 80,
        "Nieuw": null
    },
    {
        "id": 374,
        "volgnummer": 208,
        "product": "Draadloze Muis 155 blauw",
        "omschrijving": "Platte draadloze muis met scrollweel. Leverbaar in drie vrolijke kleuren. Dit is de BLAUWE uitvoering<br \/><br \/>Scrollweel dient ook als middelse muisknop.<br \/>Inclusief dongle (te bewaren in de muis) en 2 Alkaline batterijen. Dus direct klaar voor gebruik. Geen software te installeren.<br \/><br \/>Werkt met Chromebook, Apple en windows pc.<br \/><br \/>Download de PDF voor meer info",
        "categorie": "muizen",
        "type": "draadloos",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "132.6000",
        "prijsperstuk": "5.6900",
        "verzendkosten": null,
        "bestelhoeveelheid": 20,
        "leverancier": "anda",
        "picture": "~\/images\/blauw.jpg",
        "pdf": "~\/pdffiles\/Muis155c.pdf",
        "prijs2": "240.8000",
        "bestelhoeveelheid2": 40,
        "prijs3": "455.2000",
        "bestelhoeveelheid3": 80,
        "Nieuw": null
    },
    {
        "id": 375,
        "volgnummer": 209,
        "product": "Draadloze Muis 155 geel",
        "omschrijving": "Platte draadloze muis met scrollweel. Leverbaar in drie vrolijke kleuren. Dit is de GELE uitvoering.<br \/><br \/>Scrollweel dient ook als middelse muisknop.<br \/>Inclusief dongle (te bewaren in de muis) en 2 Alkaline batterijen. Dus direct klaar voor gebruik. Geen software te installeren.<br \/><br \/>Werkt met Chromebook, Apple en windows pc.<br \/><br \/>Download de PDF voor meer info",
        "categorie": "muizen",
        "type": "draadloos",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "132.6000",
        "prijsperstuk": "5.6900",
        "verzendkosten": null,
        "bestelhoeveelheid": 20,
        "leverancier": "anda",
        "picture": "~\/images\/geel.jpg",
        "pdf": "~\/pdffiles\/Muis155c.pdf",
        "prijs2": "240.8000",
        "bestelhoeveelheid2": 40,
        "prijs3": "455.2000",
        "bestelhoeveelheid3": 80,
        "Nieuw": null
    },
    {
        "id": 376,
        "volgnummer": 210,
        "product": "Draardloze Muis 155 assortiment",
        "omschrijving": "Platte draadloze muis met scrollweel.<br \/>Assortiment van alle drie de kleuren. <br \/><br \/>Scrollweel dient ook als middelse muisknop.<br \/>Inclusief dongle (te bewaren in de muis) en 2 Alkaline batterijen. Dus direct klaar voor gebruik. Geen software te installeren.<br \/><br \/>Werkt met Chromebook, Apple en windows pc.<br \/><br \/>Download de PDF voor meer info",
        "categorie": "muizen",
        "type": "draadloos",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "132.6000",
        "prijsperstuk": "5.6900",
        "verzendkosten": null,
        "bestelhoeveelheid": 20,
        "leverancier": "anda",
        "picture": "~\/images\/ass.jpg",
        "pdf": "~\/pdffiles\/Muis155c.pdf",
        "prijs2": "240.8000",
        "bestelhoeveelheid2": 40,
        "prijs3": "455.2000",
        "bestelhoeveelheid3": 80,
        "Nieuw": null
    },
    {
        "id": 377,
        "volgnummer": 147,
        "product": "USB Geluidskaart",
        "omschrijving": "Stekker afgebroken in een chromebook of laptop hoofdtelefoon aansluiting defect? Dit is de oplossing!<br \/><br \/>Een compacte USB audio adapter.<br \/><br \/>Download de PDF voor alle informatie<br \/><br \/>Sluit aan op een vrije USB poort en maak zo een vervangende hoofdtelefoon en\/of microfoonaansluiting.<br \/><br \/>Handig als de originele hoofdtelefoon aansluiting kapot of geblokkeerd is. <br \/><br \/>Plug & Play. Insteken en meteen gebruiksklaar.",
        "categorie": "hoofdtelefoon accessoires",
        "type": "geluidsoplossing",
        "eigenschap": null,
        "groep": "winkelier",
        "prijs": "40.0000",
        "prijsperstuk": "8.0000",
        "verzendkosten": "4.9500",
        "bestelhoeveelheid": 5,
        "leverancier": "Nedis",
        "picture": "~\/images\/3dsound.png",
        "pdf": "~\/pdffiles\/USB Geluidskaart11052022.pdf",
        "prijs2": null,
        "bestelhoeveelheid2": null,
        "prijs3": null,
        "bestelhoeveelheid3": null,
        "Nieuw": null
    }
]